import d12
nhap_n = input("Nhap day so nguyen cach nhau bang dau phay:")
ds = d12.taolist(nhap_n)
print("Danh sach:",ds)
# print("So lon nhat chia het cho 3:",d12.max_chiahe3(ds))
# # print("So chinh phuong :",d12.scp(ds))
# x = int(input("Nhap so x:"))
# print(f"so {x} nam o vi tri thu {d12.vitricuoicung(ds,x)}")
# print("So nho nhat trong cac so duong:",d12.min_soduong(ds))
# print("Giai thua cua cac so :",d12.giaithua(ds))
# x = int(input("Nhap so x de xoa:"))
# print(f"Danh sach sau khi xoa {x}:",d12.kt_x(ds,x))
# print("Trung binh cong cac so chia het cho 3:",d12.tbc_chiahetcho3(ds))
# print("So xuat hien nhieu nhat:",d12.so_xhmax(ds))
print("Danh sach sau khi xoa o vi tri 3:",d12.xoaso_vitri3(ds,3))