import d2
lst = d2.nhapdayso()
print("Danh sach da nhap:", lst)
print("Danh sach sau khi xoa phan tu am trong mang:",d2.xoa_ptuam(lst))
# x = int(input("Nhap so X de dem:"))
# print(f"So lan xuat hien cua {x} trong danh sach la:",d2.count_x(lst,x))
# print(f"So {x} nam o vi tri {d2.vitri_x(lst,x)}")
# print("So luong phan tu khac nhau trong danh sach la:",d2.count_phantukhac(lst))
# print("Danh sach sau khi xoa tat ca cac phan tu:",d2.xoa_tatcaphantu(lst))
# print("Trung binh cong cac phan tu chia het cho 3:",d2.tbc_chia3(lst))
# print("Danh sach sau khi xoa tat ca cac phan tu duong",d2.xoa_ptuduong(lst))
# print("So chia het cho 5 cuoi cung trong danh sach:",d2.chiahet5_cuoicung(lst))
# print("Trung binh cong cac so am trong danh sach:",d2.tbc_soam(lst))
# print("Danh sach sau khi thay the so am bang 0 ta duoc",d2.thaythe_soam_thanh0(lst))
# print("Danh sach sau khi xoa cac phan tu lap:",d2.xoa_giatri_lap(lst))
# print("Phan tu duong nho nhat trong danh sach:",d2.phtu_minduong(lst))
# print("So luong cac so am lien tiep :",d2.soluong_amlientiep(lst))
# tong, tbc = d2.tongvatbc(lst)
# print(f"Tong = {tong}, Trung binh cong = {tbc}")
print("Cac so hoan hao co trong danh sach la:",d2.ktra_shh(lst))