import d3

s = input("Nhap xau con s:")
d3.hienthixaukt(s)
# d3.daonguoc_kytu(s)
# s1 = input("Nhap xau con s1:")
# d3.solanxuathiens1(s,s1)
# s2 = input("Nhap xau con s2:")
# d3.kiemtra_sbangs2(s,s2)
# d3.kytuxuathien_itnhat1lan(s)
# d3.kiemtra_batdauviethoa(s)
# d3.xaucon_danhap(s)
# d3.demchuhoa_chuthuong(s)
# d3.sx_tangdan(s)
# d3.kiemtra_ketthuc(s,s1)
# d3.kytu_xuathiennhieulannhat(s)
d3.kiemtra_tuscoviethoa(s)
# d3.tach_xau_roiin(s)
# d3.xoa_tucuoi(s)
# d3.soluongtu(s)
# s1 = input("Nhap s1 de kiem tra dao nguoc:")
# d3.kiemtra_daonguoc(s,s1)
# d3.kiemtra_chuoidx(s)
# d3.xoa_tatcachuso(s)
# d3.timtunganhat(s)
# d3.dem_kytuchucai(s)
# d3.kiemtra_chuoiviethoa(s)
