import d4
s = input("Nhap xau:")
print("Ky tu da nhap",d4.in_kytu(s))
# print("So luong cac ky tu so:",d4.dem_kytu(s))
# print("Tu co nhieu ky tu nhat:",d4.kytu_nhieu(s))
# s1 = input("Nhap xau con s1:")
# print(f"{s1} co phai xau con cua {s} khong?:",d4.kt_xaucon(s,s1))
# print("Tat ca cac xau con cua khac nhau:",d4.ht_xaucon_khacnhau(s))
# print("Xau sau khi xoa tu dau:",d4.xoa_tudau(s))
# print("Xau sau khi chuyen sang ASCII:",d4.chuyendoi_ASCII(s))
# print("Ma lon nhat:",d4.ma_lonnhat(s))
# print("Danh sach:",d4.ds_dodai_tangdan(s))
# print("So luong cac ky tu dac biet:",d4.Dem_kytudacbiet(s))
# s2 = input("Nhap xau s2:")
# print(f"{s2} co nam trong s khong ?",d4.kt_trongxau(s,s2))
# print("Xau sau khi bo khoang trang o dau va cuoi:",d4.bo_khoangtrong_daucuoi(s))
# s1 = input("Nhap xau:")
# print("Tat ca vi tri cua s1 trong s :",d4.tim_vitris1(s,s1))
# print("So luong chu hoa trong s:",d4.kt_chuhoa(s))
# print("Xau sau khi thay doi:",d4.chuyentudau_thanhhoa(s))
# c = input("Nhap:")
# print(f"Vi tri cua {c} trong {s}: ",d4.timvitri_Cxuathien(s,c))
# print("Xau sau khi xoa ky tu dac biet:",d4.xoa_ktdacbiet(s))
# print("Tu dai nhat:",d4.max_kytu(s))
# print("Xau sau khi xoa tu dau tien:",d4.xoatu_dautien(s))
s1 = input("Nhap s1:")
print("Ghep:",d4.gheps_s1(s,s1))