import d1
input_string = input("Nhập vào dãy số nguyên cách nhau bằng dấu phẩy: ")
numbers = d1.convert_to_list(input_string)
print(numbers)
print("Tong va trung binh cong cac so trong danh sach la:",d1.tongvatbc(numbers))
print("Vi tri phan tu am dau tien va cuoi cung la:",d1.amdau_amcuoi(numbers))
print("So luong so duong lien tiep la:",d1.duong_lientiep(numbers))
print("Danh sach cac day so chan :",d1.dayso_chan(numbers))
print("Danh sach cac day so le :",d1.dayso_le(numbers))
print("Phan tu lon nhat va vi tri phan tu lon nhat cuoi cung:",d1.max_maxend(numbers))
print("Loai bo cac gia tri trung nhau trong danh sach:",d1.gt_trung(numbers))
print("Sap xep danh sach tang dan:",d1.sx_tang(numbers))
x = int(input("Nhap so nguyen x de chen vao trong danh sach:"))
print("Danh sach sau khi chen:",d1.chenx_tangdan(sorted(numbers),x))
print("So chinh phuong co trong danh sach la:",d1.hienthi_scp(numbers))
print("So luong phan tu dan dau dai nhat la:",d1.sl_dandau_dainhat(numbers))
print("So luong so chinh phuong la:",d1.dem_scp(numbers))
print("Sap xep danh sach giam dan:",d1.sx_giam(numbers))
k = int(input("Nhap so nguyen k de xoa phan tu o vi tri k:"))
print(f"Danh sach sau khi xoa vi tri phan tu thu {k} la {d1.xoa_k(numbers,k)} ")
print("Co cac so lap trong danh sach la:",d1.solap(numbers))
print("Dao nguoc thu tu trong danh sach:",d1.dao_thutu(numbers))
print("Cac so nguyen to co trong danh sach la:",d1.snt(numbers))
x_check = int(input("Nhap x xem x co trong danh sach khong:"))
print("Danh sach sau khi kiem tra va them x la:",d1.ktrax_danhsach(numbers,x))